# Generated by Django 6.0.5 on 2026-05-13 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Circuit",
            fields=[
                ("circuit_id", models.IntegerField(primary_key=True, serialize=False)),
                ("circuit_ref", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=256)),
                ("location", models.CharField(max_length=128)),
                ("country", models.CharField(max_length=128)),
                ("lat", models.FloatField(null=True)),
                ("lng", models.FloatField(null=True)),
                ("alt", models.SmallIntegerField(null=True)),
                ("url", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "circuit",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Constructor",
            fields=[
                (
                    "constructor_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("constructor_ref", models.CharField(max_length=64)),
                ("name", models.CharField(max_length=128)),
                ("nationality", models.CharField(max_length=64)),
                ("url", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "constructor",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ConstructorRaceResult",
            fields=[
                (
                    "constructor_result_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                (
                    "points",
                    models.DecimalField(decimal_places=2, max_digits=5, null=True),
                ),
                ("result_status", models.CharField(max_length=64, null=True)),
            ],
            options={
                "db_table": "constructor_race_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ConstructorStanding",
            fields=[
                (
                    "constructor_standing_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=7)),
                ("championship_position", models.SmallIntegerField(null=True)),
                ("position_text", models.CharField(max_length=32)),
                ("wins", models.SmallIntegerField()),
            ],
            options={
                "db_table": "constructor_standing",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("driver_id", models.IntegerField(primary_key=True, serialize=False)),
                ("driver_ref", models.CharField(max_length=64)),
                ("driver_number", models.SmallIntegerField(null=True)),
                ("code", models.CharField(max_length=8, null=True)),
                ("forename", models.CharField(max_length=64)),
                ("surname", models.CharField(max_length=64)),
                ("dob", models.DateField(null=True)),
                ("nationality", models.CharField(max_length=64)),
                ("url", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "driver",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="DriverStanding",
            fields=[
                (
                    "driver_standing_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("points", models.DecimalField(decimal_places=2, max_digits=7)),
                ("championship_position", models.SmallIntegerField(null=True)),
                ("position_text", models.CharField(max_length=32)),
                ("wins", models.SmallIntegerField()),
            ],
            options={
                "db_table": "driver_standing",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="FinishingStatus",
            fields=[
                (
                    "status_id",
                    models.SmallIntegerField(primary_key=True, serialize=False),
                ),
                ("label", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "finishing_status",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="LapTime",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "race_id",
                        "driver_id",
                        "lap_num",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("race_id", models.IntegerField()),
                ("driver_id", models.IntegerField()),
                ("lap_num", models.SmallIntegerField()),
                ("lap_position", models.SmallIntegerField()),
                ("lap_time", models.CharField(max_length=32)),
                ("milliseconds", models.IntegerField()),
            ],
            options={
                "db_table": "lap_time",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="PitStop",
            fields=[
                (
                    "pk",
                    models.CompositePrimaryKey(
                        "race_id",
                        "driver_id",
                        "stop_num",
                        blank=True,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("race_id", models.IntegerField()),
                ("driver_id", models.IntegerField()),
                ("stop_num", models.SmallIntegerField()),
                ("lap_num", models.SmallIntegerField()),
                ("clock_time", models.TimeField()),
                ("duration", models.CharField(max_length=32)),
                ("milliseconds", models.IntegerField()),
            ],
            options={
                "db_table": "pit_stop",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="QualifyingSession",
            fields=[
                ("qualify_id", models.IntegerField(primary_key=True, serialize=False)),
                ("car_number", models.SmallIntegerField(null=True)),
                ("qualify_position", models.SmallIntegerField(null=True)),
                ("q1", models.CharField(max_length=32, null=True)),
                ("q2", models.CharField(max_length=32, null=True)),
                ("q3", models.CharField(max_length=32, null=True)),
            ],
            options={
                "db_table": "qualifying_session",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Race",
            fields=[
                ("race_id", models.IntegerField(primary_key=True, serialize=False)),
                ("year", models.SmallIntegerField()),
                ("round_num", models.SmallIntegerField()),
                ("name", models.CharField(max_length=256)),
                ("race_date", models.DateField()),
                ("race_time", models.TimeField(null=True)),
                ("url", models.CharField(max_length=512)),
                ("fp1_date", models.DateField(null=True)),
                ("fp1_time", models.TimeField(null=True)),
                ("fp2_date", models.DateField(null=True)),
                ("fp2_time", models.TimeField(null=True)),
                ("fp3_date", models.DateField(null=True)),
                ("fp3_time", models.TimeField(null=True)),
                ("quali_date", models.DateField(null=True)),
                ("quali_time", models.TimeField(null=True)),
                ("sprint_date", models.DateField(null=True)),
                ("sprint_time", models.TimeField(null=True)),
            ],
            options={
                "db_table": "race",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RaceResult",
            fields=[
                ("result_id", models.IntegerField(primary_key=True, serialize=False)),
                ("car_number", models.SmallIntegerField(null=True)),
                ("grid_pos", models.SmallIntegerField()),
                ("finish_position", models.SmallIntegerField(null=True)),
                ("position_text", models.CharField(max_length=32)),
                ("position_order", models.SmallIntegerField()),
                ("points", models.DecimalField(decimal_places=2, max_digits=5)),
                ("laps", models.SmallIntegerField()),
                ("finish_time", models.CharField(max_length=64, null=True)),
                ("milliseconds", models.IntegerField(null=True)),
                ("fastest_lap", models.SmallIntegerField(null=True)),
                ("fastest_lap_rank", models.SmallIntegerField(null=True)),
                ("fastest_lap_time", models.CharField(max_length=32, null=True)),
                ("fastest_lap_speed", models.CharField(max_length=32, null=True)),
            ],
            options={
                "db_table": "race_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                ("year", models.SmallIntegerField(primary_key=True, serialize=False)),
                ("url", models.CharField(max_length=512)),
            ],
            options={
                "db_table": "season",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SprintResult",
            fields=[
                (
                    "sprint_result_id",
                    models.IntegerField(primary_key=True, serialize=False),
                ),
                ("car_number", models.SmallIntegerField(null=True)),
                ("grid_pos", models.SmallIntegerField()),
                ("finish_position", models.SmallIntegerField(null=True)),
                ("position_text", models.CharField(max_length=32)),
                ("position_order", models.SmallIntegerField()),
                ("points", models.DecimalField(decimal_places=2, max_digits=5)),
                ("laps", models.SmallIntegerField()),
                ("finish_time", models.CharField(max_length=64, null=True)),
                ("milliseconds", models.IntegerField(null=True)),
                ("fastest_lap", models.SmallIntegerField(null=True)),
                ("fastest_lap_time", models.CharField(max_length=32, null=True)),
            ],
            options={
                "db_table": "sprint_result",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="RaceNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("race_id", models.PositiveIntegerField()),
                ("body", models.TextField(max_length=2048)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="race_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "racing_race_note",
                "ordering": ["-updated_at"],
            },
        ),
    ]
